### ISSUE TITLE
Armor Obsession

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#11]
In the 1.9.1 Version I added an opposite trait to shield_obsessed. armor_obsessed, its debuffs aren't as punishing as shields because armor doesn't regenerate, but I think it was a decent addition.

trait_armor_obsessed = {
	ship_shield_mult 	= -0.5
	ship_armor_mult 	= 4
	ship_armor_add 	= 1
}

The flavour text needed work, sounded a bit Too similar to the other one only opposite, but then again, writing was never my specialty.

 trait_armor_obsessed:0 "Obsessed with Armor"
 trait_armor_obsessed_desc:0 "§LThis species never cared for fantasy equipment like shields. They shun even the concept of energy shielding in favour of physical armor protection"\n\n -50% shield power, +400% armor  §!\n"

**Comment by LuxArdens** [comment]
Good trait idea. Though I'd make the shield debuff a full -100% though. In the new patch armour slots are only marginally weaker than shields, so seeing how the main purpose is tactical (combat strength), +400% armour is probably vastly more useful than the strategic advantage of regenerative ability. I'll pit some ships against each other later on to confirm.

**Comment by TvoEx** [comment]
Will implement when I have the chance

**Comment by LuxArdens** [comment]
Did you have an icon for it? Because I can make one in a couple minutes

**Comment by LuxArdens** [comment]
Nvm, just went ahead and added it

**Comment by TvoEx** [comment]
Right, was at work and couldn't do much there besides commenting.

**Comment by LuxArdens** [comment]
No problem, I just felt like doing it. All the necessary files are in now, but it doesn't actually work. For some reason the event that adds the static modifier doesn't do anything. I'm having more problems with events, so you may want to take a look at them in "trait.txt" and "planet_regulation.txt"
