### ISSUE TITLE
Missing City color LUT textures for Heavy

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#12]
City color LUT textures are missing for Toxic, Molten, Frozen, Barren, Gas giants and Stars. Leading to the leader portrait freezing up in the country creation screen. Bug or Wontfix?

**Comment by LuxArdens** [comment]
It's because the city overlay is disabled for those. I'll re-enable it for Toxic, Molten, Frozen, Barren; have to check whether Gas Giant, Star and Asteroid look acceptable, but probably not, so that's a lose-lose situation.

**Comment by TvoEx** [comment]
Just threw some LUT textures in for testing, Gas giants look terrible, asteroids look acceptable because it overlays the city, thus no ugly floating city sprites to look at. Seems like the best fix for stars and gas giants is no city sprite at all.

**Comment by TvoEx** [comment]
And that's exactly what I did, Gave everything a LUT texture and the ones that looked terrible simply don't show a city anymore. Better this than breaking animations in my opinion.

**Comment by LuxArdens** [comment]
> Seems like the best fix for stars and gas giants is no city sprite at all.

Cities inside a stellar core made little sense anyway XD
