### ISSUE TITLE
Reduce occurrence of Star and Gas giant prefs

### ISSUE THREAD

**Issue by LuxArdens** [LuxArdens/Stellaris---RPG-Traits-mod#14]
Stellar preference and such are occurring too often. Need to find a way to regulate it, like the normal traits. Hab traits are currently not assigned through custom event but by some hidden game mechanic which probably needs to be killed somehow.

Apparently hab traits now have an 'ai_weight'. Might be usable. Going to plug in conditional modifiers as well and see if the game responds to that.

**Comment by LuxArdens** [comment]
Can't be regulated as planet selection and placement is done before game start. Hab picks are random with no way to influence or weigh picks. Applying partial fix only; custom made races still provide a solution for people who want their species to be perfect.

**Comment by LuxArdens** [comment]
Reopened. Going to make a post-gamestart regulation event to enforce some planet diversity.

**Comment by LuxArdens** [comment]
Wrote completely new system based on chain of events on game start, to re-assign some species planet preference. **Not working, for unknown reasons**. Game 'cannot find event' even when triggered using console. Encountered that one before, but not sure what causes it; events are based on the template for trait regulation events, which do work.

**Comment by TvoEx** [comment]
I was able to execute all 4 of the planet regulation events.

**Comment by LuxArdens** [comment]
See that's really weird. You can fire the events but my game can't fire them. I've encountered this bug before but I forgot what it was about. It's like the game makes its own 'event cache' that refuses to update sometimes.

Anyway good to see it's working somewhat. I won't be able to fix it entirely for as long as my game acts weirdly. Robots with traits are intentional btw. In the Heavy version they need those too because they don't get a straight up +200% hab bonus just for being mechanical anymore. I do intend to separate their hab traits from the organics though.

**Comment by LuxArdens** [comment]
Planet regulation events are now at full functionality. Encountered zero bugs in total of 60 randomly spawned empires. Only standard races for now, might add FE later. Great succes either way.
