### ISSUE TITLE
Organic pops cannot survive on Machine worlds

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#16]
Even when selected as their natural Homeworld, their preference doesn't seem to work, Is this intended or a bug?

**Comment by LuxArdens** [comment]
Not intended. Probably another hidden, undocumented habitability modifier (2.0 introduced many). I'll correct the trait to counter it.

**Comment by LuxArdens** [comment]
Problem found. Proper name is pc_ai not pc_machine. pc_machine is hardcoded at zero habitability for some special event chain

**Comment by LuxArdens** [comment]
Fixed, and added some fancy descriptions as well
