### ISSUE TITLE
Question about a lack of adaptability traits

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#18]
_Question forwarded from steam workshop_
From: **Verdant Squire **
whats up with the lack of adaptability traits? Those were my favorite pick in the base game, and the "toughness" traits don't really stratch the same itch they did.

**Comment by LuxArdens** [comment]
Toughness is literally the same as adaptability for all intents and purposes, just with some added army bonuses because if they can survive on a toxic world without a gas mask, they'd probably make slightly better soldiers too.
