### ISSUE TITLE
Rogue Servitor bug

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#20]
_Bug report forwarded from steam workshop_
From: **arkanrium**
Seem this is making the Rogue servitor bio-trophy bonus to not work for some reason.

**Comment by TvoEx** [comment]
Found the source of the bug, just about everything in our vanilla static modifier overrides are out of date

**Comment by TvoEx** [comment]
Just asking, seems like alot of work patching the mod can be voided by not having these.

**Comment by LuxArdens** [comment]
I tweaked the happiness and hab modifiers in those to better suit Heavy. Tweaks have now been properly ported to new static modifiers, so bug should be fixed.
