### ISSUE TITLE
Meta - random Github rubbish in code 

### ISSUE THREAD

**Issue by LuxArdens** [LuxArdens/Stellaris---RPG-Traits-mod#24]
Github seems to insert stuff like "<<<<<<< HEAD" into the code whenever a merge takes place. Do you know what causes that and how to prevent it?

**Comment by TvoEx** [comment]
May have something to do with the fact that Github thinks this is AMPL code.

**Comment by LuxArdens** [comment]
Wut. How? Why? Where do you see that?

**Comment by TvoEx** [comment]
Click on your profile and look at your repos, it will probably say this is an AMPL repository

The headers may be completely unrelated, just a random thought.

**Comment by KaySackey** [comment]
If you merge via the web interface and elect to ignore conflicts then you will see this.

**Comment by LuxArdens** [comment]
Ah, so it's my fault then. Cheers!
