### ISSUE TITLE
AI genemodding itself Lobotomized

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#25]
AI Seems to love lobotomizing itself at random the moment they get the tech to genemod. AI races that do this usually very quickly afterwards get curbstomped or become a protectorate of a stronger empire.

**Comment by TvoEx** [comment]
This is in fact so common that it happens at least once to some poor AI every playthrough. Poor bastards don't know what they're doing. Took pity on one of them and made them my protectorate, eventually integrated them and fixed their error before releasing them back into the wild.

**Comment by LuxArdens** [comment]
Hahaha, oh wow. I guess that's because I put the cost of lobotomizing at zero. This was to ensure you could apply it to conquered races and primitives even without having the "advanced genemodding" tech. I'll see if I can prevent AI from picking it, but that's probably not too easy.

**Comment by LuxArdens** [comment]
Put lobotomite back at -1 cost for now, so AI recognizes it as a baaad trait. Ideally I'd have lobotomite be available before advanced genemodding though, otherwise it's a rather pointless trait. Will try to think of some way for this; probably gonna turn it into a species_right instead.
