### ISSUE TITLE
Ascension paths missing

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#26]
Ascension paths for Psionics and Evolution are missing.

**Comment by LuxArdens** [comment]
Cannot replicate this.

Ascension paths only had their exclusions modded so that Psionic and Evolution are not mutually exclusive.

**Comment by TvoEx** [comment]
I don't know what to tell you other than they are gone from the selection, only starting a new game in vanilla makes them appear.

**Comment by TvoEx** [comment]
I'm not the only one to have noticed this.

**Comment by TvoEx** [comment]
NEVERMIND. Was being silly, I cant get them because of that cybernetic trait my race had..

Putting that information on the localization could help avoid this confusion in the future.

**Comment by TvoEx** [comment]
And that's exactly what I did.

**Comment by LuxArdens** [comment]
XD I suspected that already when trying to replicate. There's already a tooltip for it when you hover over the locked ascension path, but instead of graying it out, they removed the AP completely as soon as you actually get Cybernetics
