### ISSUE TITLE
Steam comments that aren't very trait_smart1

### ISSUE THREAD

**Issue by LuxArdens** [LuxArdens/Stellaris---RPG-Traits-mod#27]
Compiling a selection of 'edge of the bell curve' comments, from people that clearly haven't tried the mod, or don't read before complaining or asking, or just say straight up rubbish. Because why get annoyed when you can have a good laugh about it?

>The ominvore trait, giving bonus growth speed, appears to have no effect in game.

There is no omnivore trait

>whats up with the lack of adaptability traits?

>does this mod loer the music volume?

>Interesting collection of traits, but can we please have a version without the silly and cheaty stuff? I dread what the computer could do with them selecting randomly.

>You need to remove the Masohist Trait from AI's and possibly hive minds anything that Has no need for ethics attraction. its just rediculusly OP.

**Comment by TvoEx** [comment]
I try to answer any questions if I can when I get on because some are actual valid bug reports and very rarely they have actual decent suggestions

**Comment by LuxArdens** [comment]
I know and I surely appreciate it! I deliberately evade Steam for its comment section. If you have 3000 subscribers, then the bottom 1% will give you a big load of very stupid comments, and I wanted to have a laugh about them.

**Comment by LuxArdens** [comment]
Could you maybe edit the description on the Steam pages? I think the two versions could use cross-links to each other, so people are aware there is an expanded version (Heavy version is significantly lagging in subscribers on steam, whereas on the Nexus pretty much everyone downloads both).

A clear link to the subreddit wouldn't hurt either, so people can get additional information and discussion and stuff.

**Comment by TvoEx** [comment]
The 2 versions have cross links now as well as one to the subreddit

**Comment by LuxArdens** [comment]
>the addon traits for robots are not working, I think because they have the same name as the vanilla robot traits. For example, this mods mass produced trait and the one in vanilla have the same name but it doesnt replace the vanilla one, so when you select it the game resets it to the vanilla version rather than this mods version and you cant select it. Please fix this.

Mod conflict.

>The traits show up fine in the empire creation menu, but when starting the game not a single AI empire will have any traits. Doesn't seem to be an issue on my end since I wiped everything, so I'll probably just give this mod a couple weeks before trying again >.>

This guy probably checked the AI races at the first day, when they indeed have no traits. Or mod conflict.

>I think the Tiny mod is bugged for AI empires. It applies the tiny modifier twice for mineral gains. -75% and -80%, guessing it's been forgotten after a tweek?

Nope it doesn't. Proooobably a mod conflict.
