### ISSUE TITLE
Question from the workshop

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#29]
_Question forwarded from steam workshop_
From: **Saboras**

Hi,
I'm making my own trait and civic mod at the moment and since I suck at creating icons, I wanted to ask you if I can use some resources, like trait and building icons, of your mod for mine.

**Comment by LuxArdens** [comment]
No problem. I believe I only have custom trait icons though, no other stuff.
