### ISSUE TITLE
MP Desync issues

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#30]
_Error Report forwarded from steam workshop_
From: **Joker**

Currently getting this error, which is traced back to this mod sadly. It's causing out of sync errors for multiplayer games. It spams the error log with thousands of errors per second.

[09:43:07][trigger_impl.cpp:793]: Script Error: Invalid context switch[owner], file: events/trait.txt line: 716, Scope: 

[09:43:07][trigger_impl.cpp:794]: type=planet
id=948

Any idea for a fix? No other mod conflicts.

**Comment by TvoEx** [comment]
This specific event id is `trait.8333` line 716 being `owner = { has_trait = trait_living_planet }`

**Comment by TvoEx** [comment]
The issue isn't the code not working, its the fact that its checking every planet where the conditions cant be meet. Adding the line `has_owner = yes` before `owner = { has_trait = trait_living_planet }` seems to fix the issue

**Comment by LuxArdens** [comment]
Nice work on that one
