### ISSUE TITLE
Species spawning without traits

### ISSUE THREAD

**Issue by LuxArdens** [LuxArdens/Stellaris---RPG-Traits-mod#31]
Don't have time to hunt for the cause right now, but looks like the trait assignment system broke.

**Comment by TvoEx** [comment]
Works just fine in Heavy

**Comment by LuxArdens** [comment]
Nvm, can't replicate it anymore either.

**Comment by LuxArdens** [comment]
Confirmed cause. They spawn just fine, but the AI doesn't know how to genemod for shit, so occasionally it'll revert its species back to the original (empty) template for no reason.
