### ISSUE TITLE
Machine races & Titanic and Tiny

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#36]
If a machine race has Titanic, its base 500% production bonus will stack with its pop_robot_production_output = 5 resulting in a total 1000% bonus, Tiny is the other way around with machine races making literally 0 minerals on planets.

The issue is, if this line is removed, Then organic Tiny/Titanic robots in particular wont have their race's tiny or titanic bonus.

This among other things was a reason I separated trait_titanic and trait_robo_titanic when I first implemented it with machine races in 1.9

**Comment by TvoEx** [comment]
High Prio as it breaks machine Tiny making that trait unplayable with machines.

**Comment by TvoEx** [comment]
Issued a quick fix for now, Organic titanic and tiny will have baseline robot production modifiers.

**Comment by LuxArdens** [comment]
On it.

**Comment by LuxArdens** [comment]
Traits split into Machine and Organic versions. Fixed Eggborn and Tiny colony ship build speed while at it.
