### ISSUE TITLE
user_empire_designs

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#39]
The addition of user_empire_designs permanently deletes any custom species you have made in the past even when you disable the mod. 
The readme was updated to reflect this but it is in the mod folder itself and I wasn't aware of its existance, anyone who activates the mod without deleting the file first will lose all their custom species permanently.

**Comment by TvoEx** [comment]
sigh, now I have to go tell the people there is no fix for their custom species being gone, I always wanted to provide the most up-to-date version to steam so people can enjoy the latest features as quickly as possible. 

This time it really bit me in the ass.

**Comment by LuxArdens** [comment]
Ow shit. I couldn't have guessed it would automatically overwrite the file in the Stellaris folder. Didn't become apparent in my own playtesting either as the file's identical to the one in my Stellaris folder of course. 

I've renamed the file now, but that really sucks for the people who had lots of custom species and activated it.

**Comment by LuxArdens** [comment]
@TvoEx I assume you've already removed the file from the Steam version?

**Comment by TvoEx** [comment]
As soon as I found out yes.
