### ISSUE TITLE
One reported instance of test trait in real game.

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#40]
_Bug report forwarded from steam workshop_
Reportee: **Comnislasher**
Somehow one of my vassals ended up with trait_effect_supercheat. Imagine my surprise when he waltz in with several 17m fleets

**Comment by LuxArdens** [comment]
That's weird. I actually completely commented that trait and moved it to a separate, personal mod for testing instead. I'll comment the rest of the events and modifiers related to it as well.

**Comment by LuxArdens** [comment]
And done. Can't help but wonder how that happened in the first place though. Maybe some weird vanilla glitch at work there.
