### ISSUE TITLE
planet habitabilities

### ISSUE THREAD

**Issue by SiceX** [LuxArdens/Stellaris---RPG-Traits-mod#43]
For some reason, the game doesn't recognise the names of the planet class preference traits.
Here's an extract from the log:

[15:51:36][persistent.cpp:34]: Error: "Unexpected token: trait_pc_desert_preference, near line: 15
" in file: "common/traits/01_species_traits_habitability.txt" near line: 63
[15:51:36][persistent.cpp:34]: Error: "Unexpected token: trait_pc_arid_preference, near line: 64
" in file: "common/traits/01_species_traits_habitability.txt" near line: 111

This results in blank pc preference traits without modifiers, effectively preventing every race from colonizing other planets.
The fact is, I really can't understand why the game does that, tha trait names are even the same as the original ones.
Any idea?

**Comment by SiceX** [comment]
Found the culprit and fixed it, opened new pull request.

**Comment by LuxArdens** [comment]
Hey SiceX!

Can't check your fix until next week, but I trust it's good work as usual and I'll join you in updating the mod to the latest version

Cheers,
LuxArdens
