### ISSUE TITLE
Irradiated Trait not working

### ISSUE THREAD

**Issue by KubiG37** [LuxArdens/Stellaris---RPG-Traits-mod#48]
Description of the issue
#######################
I found that this trait has a duplicate entry in common\traits\RPGT_species_traits.txt , deleting the first entry fixes it.

Steps to reproduce
#######################
If you assign Irradiated trait to a species in custom empire, and reload a game, the game locks the custom empire with a bug warning.

Game version and mods in use
#######################
2.1.2

**Comment by LuxArdens** [comment]
Should be fixed now
