### ISSUE TITLE
Re-organized trait selection file

### ISSUE THREAD

**Issue by TheLynx01** [LuxArdens/Stellaris---RPG-Traits-mod#52]
Wasn't quite certain how else to send this to you, as I'm still relatively new to these sites:

Here is the RPGT_species_traits file with the updated and reformatted order of traits.

[RPGT_species_traits.txt](https://github.com/LuxArdens/Stellaris---RPG-Traits-mod/files/2515980/RPGT_species_traits.txt)

To the best of my knowledge, I didn't accidentally drop any traits in the process (all un-used, commented out traits are collected at the bottom in the 'Disabled Traits' section), but you may want to double check my work to make sure I didn't break something along the way.

**Comment by LuxArdens** [comment]
Looks all good, except it's the version that has the order as

-1
-2
-3
1
2
3

instead of the other one. I liked that one better but I'll sort it out later along with some other stuff. Thanks for the addition!

**Comment by TheLynx01** [comment]
[RPGT_species_traits.txt](https://github.com/LuxArdens/Stellaris---RPG-Traits-mod/files/2548831/RPGT_species_traits.txt)

Here is the corrected file with the 
-3, -2, -1 ordering

**Comment by LuxArdens** [comment]
Cheers!
