### ISSUE TITLE
Unable to create vassals

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#9]
In 2.0.0 The ability to vassalize and make tributaries is unlocked by adopting the tradition of domination, are we overwriting the traditions with the old one?

**Comment by LuxArdens** [comment]
We used to a long time ago, but not in 2.0.0, so probably not RPGT

**Comment by TvoEx** [comment]
Source of bug is vanilla 2.0.0 Machine races vassalization doesnt get unlocked with supremacy
